### ISSUE TITLE
How can this programmer be repaired, as it stopped working while working with the programmer reader ?  It does not issue any command. I did everything in my power, and unfortunately I made sure that it stopped working. I bought it 2 weeks ago and it stopped working after 12 days

### ISSUE THREAD

**Issue by MzElhout** [BetterWayElectronics/ps4-syscon-reader-writer#1]
![image](https://user-images.githubusercontent.com/129943391/230037549-f4e57d9d-56ba-44de-8afb-e6b02fa6305c.jpeg)

**Comment by BetterWayElectronics** [comment]
1. This git is for the software only and thus your question is not relevant here
2. You overwrote the code of the Arduino and blanked it, the software will not function with a blank Arduino.
3. You were spoken to privately about this at length and refused to listen and accept any solution and were subsequently blocked
4. You are pretending to not know the issue, see #3 and #2
